import { Home } from "@/components/icons";
export const LastRecData = [
  {
    header: "Last Records",
    color: "",
    icon: <Home />,
    has: "-",
    num: " 1,000₮",
    p: "3 hours ago",
    h1: "Lending & Renting",
  },
  {
    header: "Last Records",
    color: "",
    icon: <Home />,
    has: "-",
    num: " 1,000₮",
    p: "3 hours ago",
    h1: "Lending & Renting",
  },
  {
    header: "Last Records",
    color: "",
    icon: <Home />,
    has: "-",
    num: " 1,000₮",
    p: "3 hours ago",
    h1: "Lending & Renting",
  },
  {
    header: "Last Records",
    color: "",
    icon: <Home />,
    has: "-",
    num: " 1,000₮",
    p: "3 hours ago",
    h1: "Lending & Renting",
  },
  {
    header: "Last Records",
    color: "",
    icon: <Home />,
    has: "-",
    num: " 1,000₮",
    p: "3 hours ago",
    h1: "Lending & Renting",
  },
  {
    header: "Last Records",
    color: "",
    icon: <Home />,
    has: "-",
    num: " 1,000₮",
    p: "3 hours ago",
    h1: "Lending & Renting",
  },
];
